using API.Models;
using API.Utilities.Enums;

namespace API.DTOs.Employees;

public class NewEmployeeDto
{
    public NewEmployeeDto()
    {
        // Generate NIK di sini (misalnya dengan menggunakan metode atau algoritma)
        NIK = GenerateAutoGeneratedNIK();
    }
    public string NIK { get; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime BirthDate { get; set; }
    public GenderLevel Gender { get; set; }
    public DateTime HiringDate { get; set; }
    public string Email { get; set; }
    public string PhoneNumber { get; set; }

    private static string GenerateAutoGeneratedNIK()
    {
        // Implementasikan logika generasi NIK di sini
        // Untuk keperluan contoh, mari asumsikan NIK berupa angka acak dalam rentang tertentu.

        string randomPart = new Random().Next(100000, 999999).ToString();

        return randomPart;
    }

    public static implicit operator Employee(NewEmployeeDto newEmployeeDto)
    {
        return new Employee
        {
            NIK = newEmployeeDto.NIK,
            Guid = new Guid(),
            FirstName = newEmployeeDto.FirstName,
            LastName = newEmployeeDto.LastName,
            BirthDate = newEmployeeDto.BirthDate,
            Gender = newEmployeeDto.Gender,
            HiringDate = newEmployeeDto.HiringDate,
            Email = newEmployeeDto.Email,
            PhoneNumber = newEmployeeDto.PhoneNumber,
            CreatedDate = DateTime.Now,
            ModifiedDate = DateTime.Now
        };
    }

    public static explicit operator NewEmployeeDto(Employee employee)
    {
        return new NewEmployeeDto
        {
            FirstName = employee.FirstName,
            LastName = employee.LastName,
            BirthDate = employee.BirthDate,
            Gender = employee.Gender,
            HiringDate = employee.HiringDate,
            Email = employee.Email,
            PhoneNumber = employee.PhoneNumber
        };
    }
}